name: Doxygen Documentation

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-doxygen-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        doxyfile-path: ./Doxyfile
        working-directory: .
